# Generated by Django 3.1.6 on 2021-02-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(max_length=10)),
                ('currency_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('bought_at_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('operation_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
