# Generated by Django 3.1.6 on 2021-02-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpackage',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
    ]
