# Generated by Django 3.1.6 on 2021-02-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20210203_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCryptocurrencyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('instant', models.DateTimeField(blank=True, null=True)),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('buy_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
