# Generated by Django 3.1.6 on 2021-02-16 10:03

from django.db import migrations

from shared.domain.dependencies import dependency_dispatcher
from trading.application.django_models import DCryptocurrencyPrice
from trading.domain.interfaces import ICryptoCurrencySource


def _do_migrate(apps, schema_editor):
    trading_source: ICryptoCurrencySource = dependency_dispatcher.request_implementation(ICryptoCurrencySource)
    for currency in trading_source.get_trading_cryptocurrencies():
        prices = trading_source.get_last_month_prices(currency)
        print(f'Migrating {currency}')
        for p in prices:
            DCryptocurrencyPrice.objects.create(
                symbol=p.symbol,
                instant=p.instant,
                sell_price=p.sell_price,
                buy_price=p.buy_price,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_dcryptocurrencyprice'),
    ]

    operations = [
        migrations.RunPython(_do_migrate)
    ]
