# Generated by Django 3.1.4 on 2020-12-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dserverconfiguration',
            options={'verbose_name': 'Server configuration', 'verbose_name_plural': 'Server configurations'},
        ),
        migrations.AlterModelOptions(
            name='duserconfiguration',
            options={'verbose_name': 'User configuration', 'verbose_name_plural': 'User configurations'},
        ),
    ]
