# Generated by Django 3.1.6 on 2021-02-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_auto_20201216_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(db_index=True, max_length=255)),
                ('text', models.TextField(default='')),
            ],
            options={
                'ordering': ('-instant',),
            },
        ),
    ]
