# Generated by Django 3.1.6 on 2021-02-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_dsystemlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsystemlog',
            options={'ordering': ('-instant',), 'verbose_name': 'System Log', 'verbose_name_plural': 'System Logs'},
        ),
    ]
